<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUx0xZe5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUx0xZe5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUx0xZe5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUx0xZe5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUx0xZe5\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'Ux0xZe5',
    'container.build_id' => 'e06c381c',
    'container.build_time' => 1546959772,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUx0xZe5');
